- hosts: siltef_1311
- become: no
- vars:
    #rede: "{{ }}"
    caminho: "/home/procergs/alexsandro-righi/fw.sh"
- tasks:
  - name: "Adicionar nova rede a lista de bloqueio do iptables"
  - shell: "cat {{ caminho }} "
    register: saida
    debug:
      msg: "Resultado do cat {{ saida }}"
