- hosts: all
  vars:
    rede: "{{ }}"
    caminho: "/home/alex/fw.sh"
  tasks:
  - name: "Adicionar nova rede a lista de bloqueio do iptables"
    blockinfile:
      path: "{{ caminho }}"
      insertafter: "autorizado_http=("
      block: |
        {{ rede }}
  - name: "Exibição de saída"
    debug:
      msg: "Resultado do cat {{ saida }}"
