- hosts: ser_lab
- become: no
  vars:
    #rede: "{{ }}"
    caminho: "/home/alex/fw.sh"
  tasks:
  - name: "Adicionar nova rede a lista de bloqueio do iptables"
    shell: "cat {{ caminho }} "
    register: saida
  - name: "Exibição de saída"
    debug:
      msg: "Resultado do cat {{ saida }}"
