- hosts: ser
  vars:
    rede: "{{ }}"
    caminho: "/home/alex/liberado_http.txt"
  tasks:
  - name: "Adicionar nova rede a lista de bloqueio do iptables"
    blockinfile:
      state: present
      dest: "{{ caminho }}"
      block: |
        "{{ rede }}""
